### ISSUE TITLE
Botão de pegar o link direto falha de maneira errática

### ISSUE THREAD

**Issue by villares** [webtiras/pycomic#5]
Pedi ao  @vamoss uma versão do código sem o uso do tinyURL para testar

```
function set_qs(settings) {
    var qs_array = [];
    var keys = Object.keys(settings);
    for(i=0; i<keys.length; i++) {
        var key = keys[i];
        var value = settings[key];
        qs_array.push(key + '=' + encodeURIComponent(value));
    }
    var old_url = window.location.href.split('?');
    var new_url = old_url[0] + '?' + qs_array.join('&');

    $('#direct-link').attr('href', new_url);
    $('#direct-link').text("link para esta tirinha");  # era data antes, pode ser new_url também
    $('#twitter-button').html('<a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="Confira esta tirinha sobre Python..!"data-hashtags="pycomic" data-show-count="false">Tweet</a>< async src="https://platform.twitter.com/widgets.js" charset="utf-8"></>');
    twttr.widgets.load();
}
```

UPDATE: Fiz o ajuste sugerido pelo Carlos.

**Comment by villares** [comment]
Reverti... https://github.com/webtiras/pycomic/commit/7ce3db9131d19899df7ecc078c8233215750b3eb

Podem tentar de novo aí quem quiser :)

Eu mal consigo por ; no final das linhas em JS...

**Comment by Vamoss** [comment]
Foi mal, não consigo entrar nesse nível de colaboração agora. Pra resolver o erro vc pode substituir data por new_url

**Comment by villares** [comment]
Valeuzão Carlos ajudou demais já, muito obrigado mesmo.

**Comment by villares** [comment]
Com a dica do Carlos eu arrumei o link (mas o botão do Twitter piorou) entao eu desliguei o botão do Twitter!
talvez o @rodjuncode me salve :rofl:

**Comment by villares** [comment]
vou fechar com este PR do @rodjuncode , se der algum problema reabrimos https://github.com/webtiras/pycomic/pull/6
